### ISSUE TITLE
Better abbreviate URIs

### ISSUE THREAD

**Issue by nichtich** [nichtich/wdq#13]
RDF::Query does not properly abbreviate URLs in SPARQL: https://github.com/kasei/perlrdf/issues/132

We must either monkey-patch [RDF::Query::Node::Resource::as_sparql](https://metacpan.org/source/GWILLIAMS/RDF-Query-2.915/lib/RDF/Query/Node/Resource.pm#L74) or postprocess SPARQL query string with a regex.

**Comment by kasei** [comment]
The fix for this is included in RDF::Query 2.916, which is heading to CPAN right now.

**Comment by nichtich** [comment]
Thanks! I've also included your fix as conditional monkey-patch in my script to still support RDF::Query 2.902 (included in Ubuntu 14.04 LTS).
