### ISSUE TITLE
Add full SPARQL XML output format

### ISSUE THREAD

**Issue by nichtich** [nichtich/wdq#17]
By now SPARQL XML output format is only supported as pass-through of a server response.

**Comment by VladimirAlexiev** [comment]
afaik, all SPARQL servers support sparql-results-xml and sparql-results-json.
sooo, what would be the benefit if WDQ generates this? or I misunderstand something

**Comment by nichtich** [comment]
The benefit is validation and post-processing - but you are right, this is not necessary.
