### ISSUE TITLE
"help ontology" is printed twice

### ISSUE THREAD

**Issue by VladimirAlexiev** [nichtich/wdq#23]
"help ontology" prints it twice.

I like the abbreviations you're using to cram so much info in so few lines.
But please explain these:
`wdt:P_ "_", URI, _:blank`

**Comment by nichtich** [comment]
Thanks for the bug report. 

`wdt:P_ "_", URI, _:blank` was meant to describe that any Wikidata property (`P_`) can in the `wdt` namespace can
- link to a literal (e.g. `wdt:P227 "119033364"`)
- link to an URI (e.g. `wdt:P856 <https://wikimediafoundation.org>`)
- link to a blank node (e.g. `wdt:P570 _:t270917045`)

Using `_` both as placeholder and as indicator for blank nodes is misleading so I'll change the placeholder character to `*`:

```
wdt:P* "*", URI, _:blank
```

**Comment by VladimirAlexiev** [comment]
> wdt:P_ "_", URI, _:blank was meant ...

Maybe you can include in "help ontology" these examples just for this one notation?
