### ISSUE TITLE
"help output" includes color even when --no-color

### ISSUE THREAD

**Issue by VladimirAlexiev** [nichtich/wdq#24]
This `wdq --no-color help output` prints some of the lines with ANSI colors:

```
 style
     Highlight "n"←[0;34m name←[0m, "v"←[0;32m value←[0m, "i"←[0;33m identifier←[0
 error←[0m

 length
     Abbreviate long←[0;32m value←[0ms

 align
     Use "left" or "right" to align short←[0;32m value←[0ms to a given "length"

 pre/post
     Add string before/after←[0;32m value←[0m
```

Also, please add `-NC` as a shorter variant of `--no-color`

**Comment by nichtich** [comment]
Thanks, fixed in the next release. Color is disabled by default if not run on a terminal so the option `--no-color` should not needed by default. I'll add option `-M` and `--monochrome` like `jq` does.

**Comment by VladimirAlexiev** [comment]
Windows CMD is also a “terminal” but doesn’t do colors. (Addons like ConEmu do)
